In [158]:
import numpy as np
import pandas as pd

In [160]:
df = pd.read_csv("customer.csv")
df.sample(5)

age  gender review education purchased
7    60  Female   Poor    School       Yes
23   96  Female   Good    School        No
14   15    Male   Poor        PG       Yes
46   64  Female   Poor        PG        No
11   74    Male   Good        UG       Yes

In [162]:
df = df.iloc[:,2:]

In [164]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [206]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)
#test_size=0.2: This means that 20% of the data will be used for testing,
#and the remaining 80% will be used for training.

In [168]:
from sklearn.preprocessing import OrdinalEncoder

In [170]:
X_train
# X_train.shape

review education
3      Good        PG
43     Poor        PG
30  Average        UG
6      Good    School
0   Average    School
23     Good    School
29  Average        UG
28     Poor    School
9      Good        UG
45     Poor        PG
17     Poor        UG
19     Poor        PG
46     Poor        PG
40     Good    School
49     Good        UG
14     Poor        PG
15     Poor        UG
42     Good        PG
44  Average        UG
10     Good        UG
21  Average        PG
1      Poor        UG
25     Good    School
41     Good        PG
12     Poor    School
16     Poor        UG
37  Average        PG
48     Good        UG
32  Average        UG
31     Poor    School
11     Good        UG
38     Good    School
34  Average    School
35     Poor    School
22     Poor        PG
36     Good        UG
2      Good        PG
39     Poor        PG
26     Poor        PG
5   Average    School

In [172]:
X_test

review education
18     Good    School
4   Average        UG
8   Average        UG
27     Poor        PG
20  Average    School
13  Average    School
47     Good        PG
33     Good        PG
24  Average        PG
7      Poor    School

In [176]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [178]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [180]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [182]:
X_train

array([[2., 2.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [1., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [0., 1.],
       [1., 2.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.]])

In [66]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [184]:
X_test

array([[2., 0.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [0., 0.]])

In [196]:
from sklearn.preprocessing import LabelEncoder

In [198]:
le = LabelEncoder()

In [208]:
Y_train

24    Yes
19    Yes
18     No
13     No
12     No
0      No
23     No
36    Yes
1      No
45    Yes
49     No
3      No
28     No
29    Yes
2      No
35    Yes
46     No
17    Yes
32    Yes
40     No
20    Yes
5     Yes
14    Yes
26     No
42    Yes
30     No
11    Yes
48    Yes
44     No
38     No
41    Yes
4      No
39     No
21     No
16    Yes
8      No
15     No
47    Yes
34     No
9     Yes
Name: purchased, dtype: object

In [210]:
le.fit(Y_train)

LabelEncoder()

In [212]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [214]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)


In [216]:
Y_train

array([1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1])